apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pythonapps.wftech.eu
spec:
  scope: Namespaced
  group: wftech.eu
  names:
    kind: PythonApp
    singular: pythonapp
    plural: pythonapps
    shortNames:
        - pythonapp
        - pyapp
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - source
              - imageName
              properties:
                source:
                  type: string
                  description: |
                      sourceCode is the name of configMap that will be 
                      used as source code for the python application
                imageName:
                  type: string
                  description: |
                    name of the image to run
                  default: docker.io/python:3.10-slim
                timeLimitSeconds:
                  type: integer
                  minimum: 30
                  maximum: 86400
                  default: 60
                  description:
                    App timeout in seconds
                memoryLimitMib:
                  type: integer
                  minimum: 128
                  default: 512
                  description: Number of megabytes available to the job
            status:
               type: object
               # enable custom fields
               x-kubernetes-preserve-unknown-fields: true
               # but provide some basic fields
               properties:
                 jobStatus:
                   type: string
                   default: 'Undefined'
                   description: State of the job
                 jobName:
                   type: string
                   default: ''
                   description: Name of the Job object
                 jobFinishedAt:
                   type: string
                   description: Timestamp when the job finished
      additionalPrinterColumns:
        - name: Source
          type: string
          description: Name of the ConfigMap with source code
          jsonPath: .spec.source
          priority: 1
        - name: Job
          type: string
          jsonPath: .status.jobName
          priority: 1
        - name: Status
          type: string
          jsonPath: .status.jobStatus
        - name: Finished At
          type: string
          jsonPath: .status.jobFinishedAt
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
